### ISSUE TITLE
Atomic menu icons (Shadow, Flip, Invert)

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#102]
We need icons for Undo, Redo, Clear, Clear All (unless it's just double-tap on the clear icon to clear all), Invert/Complement, Shadow and Reflect.

**Comment by starakaj** [comment]
These look a little too complex to me. And I'd advise against trying to use color in these icons. Apple actually specifically recommends against color in toolbar buttons (I don't necessarily understand why), so maybe that's something to shy away from.

**Comment by mearabai** [comment]
No color, even for submenus? The top toolbar buttons would still be white, and subtle color would a way to visually distinguish between upper and lower categories, especially in the ipad version where the menus open out to the side and all all in one line...

**Comment by starakaj** [comment]
I'd have to see it, but I'd lean away from it. At the scale of an icon, I think the color unfortunately tends to reduce contrast and makes the button harder to see.

**Comment by mearabai** [comment]
Here's my final submission: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.49okcgv3y0td

**Comment by starakaj** [comment]
Hmm. I get shadow, I like shadow. I get flip (although it sort of looks like it could be invert or flip), I like flip. Invert doesn't make a lot of sense to me. I can make it make sense if I think about it really hard (something about the necklace being a three dimensional space with one dimension for onset/rest), but I don't think it's particularly memorable or strongly tied to what it does.

No love for the black and white cookie look?

**Comment by mearabai** [comment]
Black and white cookie? I'm afraid I have no idea what you are talking about.

The invert icon is meant to be a necker cube, that illusion where you can see it in one of two orientations. I guess some percentage of the population doesn't see it ever invert, so maybe this is too obscure, but I think it looks cool and am kind of grasping at straws for another succinct icon for that...Let's talk when I get in.

**Comment by starakaj** [comment]
"The invert icon is meant to be a necker cube, that illusion where you can
see it in one of two orientations. I guess some percentage of the
population doesn't see it..."

I think your love of illusions has gotten carried away. By black and white
cookie I meant a circle with one hemisphere filled and the other not.

-S

**Comment by mearabai** [comment]
I don't think that was ever on the table for inversions, it's way too
similar to the flip icon and doesn't actually demonstrate an inversion
either. I'll keep working on it until we're both happy.



On Mon, Feb 16, 2015 at 12:14 PM, Sam Tarakajian <notifications@github.com>
wrote:

> "The invert icon is meant to be a necker cube, that illusion where you can
> see it in one of two orientations. I guess some percentage of the
> population doesn't see it..."
>
> I think your love of illusions has gotten carried away. By black and white
> cookie I meant a circle with one hemisphere filled and the other not.
>
> -S
>
> On Mon, Feb 16, 2015 at 12:09 PM, mearabai <notifications@github.com>
> wrote:
>
> > Black and white cookie? I'm afraid I have no idea what you are talking
> > about.
> >
> > The invert icon is meant to be a necker cube, that illusion where you can
> > see it in one of two orientations. I guess some percentage of the
> > population doesn't see it ever invert, so maybe this is too obscure, but
> I
> > think it looks cool and am kind of grasping at straws for another
> succinct
> > icon for that...Let's talk when I get in.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/starakaj/rnecklace/issues/102#issuecomment-74565414
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/102#issuecomment-74566001>.
>



-- 
http://www.mearaoreilly.com
