### ISSUE TITLE
Make the tempo picker menu

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#131]
Implement option #1 as per Meara's awesome design https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.nymhv1t53m5g

**Comment by mearabai** [comment]
Are we still going to add polyrythmic vs. polymetric in this menu, or do you agree that it's pretty cramped as is?

**Comment by starakaj** [comment]
Fuck. Idk. We should try to get it in there I think.

**Comment by mearabai** [comment]
I think this is the layout we agreed on: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.18eboa7jx3c1

**Comment by mearabai** [comment]
The rest of the options I made are here: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.nymhv1t53m5g
