### ISSUE TITLE
Tempo Menu Icon

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#145]
Does it really look like that geezer metronome?

**Comment by mearabai** [comment]
Make a new version that's not pixelated, etc.

**Comment by mearabai** [comment]
Cheggit: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.uppm9ng3sflr

**Comment by starakaj** [comment]
I think it looks a little square, but otherwise great

**Comment by mearabai** [comment]
We can change it later if it still bothers you, but I think it all hangs better together at these dimensions.
