### ISSUE TITLE
Shorten and thin highlighting bar above top icon menu

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#176]
Currently feels cramped and distracting.

**Comment by starakaj** [comment]
Checkit now though?

**Comment by mearabai** [comment]
Great! I still think it could be narrower tho, the length of the line is currently eclipsing the icon instead of demurely pointing towards it imo...

**Comment by starakaj** [comment]
Sure thing

**Comment by starakaj** [comment]
Alright, what about now?

**Comment by mearabai** [comment]
Did you push the change yet? Not seeing it...

**Comment by starakaj** [comment]
I did push the change. I’m assuming you pulled it? It’s possible that I’ve goofed something but on my build it looks a lot skinnier. We’ll sort it when you get in.

-S

**Comment by mearabai** [comment]
Much better, closing for now! I think we'll still want to do a final pass later where we tweak stroke sizes and dimensions etc.
