### ISSUE TITLE
Write the copy for website

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#179]

**Comment by mearabai** [comment]
What are three main feature points we want to describe on the landing page?  I'm thinking algorithms, world rhythm library, and ??  Any strong feelings or thoughts on this?

**Comment by mearabai** [comment]
I roughed in some language for now, let me know if you like/dislike anything in particular: http://rhythmnecklace.com/

**Comment by starakaj** [comment]
Tiniest change of all time: could "Rhythm necklace is a sequencer for composing circular rhythmic loops" become "Rhythm necklace is a sequencer for circular rhythms" ? Circular + loops is redundant, and if you pull out the adjectives I don't think "composing a loop" is really a thing.

**Comment by mearabai** [comment]
A sequencer for creating circular rhythms? I think throwing create in there is a bit more inviting for the set of people that don't know exactly what a sequencer is. I agree with the general sentiment of your edit wholeheartedly tho.

**Comment by starakaj** [comment]
Yeah, I'm cool with that.
