### ISSUE TITLE
Make a group of curated samples

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#180]

**Comment by mearabai** [comment]
This includes coming up with filters and envelope configs to display. I'm thinking that I can't really design the sample/timbre interface until we've even decided how many filters and envelope controls we want?! Making this issue a priority to at least investigate...

**Comment by mearabai** [comment]
I added a new sample just to test out the process but it seems to be quiet and clipping a lot--I can boost the volume next time, but is there anything I'm doing with the formatting to cause the clipping? Just trying to figure out how I should format samples so they are easier to switch in and out for prototyping...

**Comment by starakaj** [comment]
I don't really know what's up with this. I'll look into it.

**Comment by starakaj** [comment]
But I think I'll make a new ticket, referring to the bug.
