### ISSUE TITLE
Pretty please add sounds to the asset catolog

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#182]

**Comment by starakaj** [comment]
Okay so unfortunately you can only have images in the asset catalogue. Sorry 'bout that. I've tried to do the next best thing. There's a file now in the repo at Rhythm\ Necklace/Assets/Sounds/test.aif. Just replace that sound (must have the same name) with whatever sound you'd like to be the "default" sound for the app.

**Comment by mearabai** [comment]
Good enough!! Thanks!
