### ISSUE TITLE
Think about copy/paste function

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#183]
We need an easy way to create related geometries at various scales

**Comment by mearabai** [comment]
Sam, please do a limited investigation into whether this is possible to do aesthetically/without using apple's copy/paste presets. If not, maybe this should be saved for 1.1?

**Comment by starakaj** [comment]
Yeeeeeeeeeeeeeeeeeeeeeeeeeah. I think this might not be as tricky as I thought it was.

**Comment by starakaj** [comment]
Okay it's really easy. Why do I complain so much?

**Comment by mearabai** [comment]
Advanced expectation management.

**Comment by starakaj** [comment]
Lol. This is already ready to test.

**Comment by mearabai** [comment]
Damn girl, you did not just think about this, you slammed it to the dome. Next, try thinking about time travel please, k thanks.
