### ISSUE TITLE
Implement the idea of accessing samples via a circle menu

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#184]
How is it accessed in relation to the pitch/timbre menu?

**Comment by mearabai** [comment]
I'm currently thinking that sample selection and timbre control are the same menu. Holler if you disagree with this premise!  Here are the beginnings of a sample/timbre menu with some thoughts and questions to solve: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.mll4nx5zuwy6

**Comment by mearabai** [comment]
As of our most recent meeting, the idea is that you select a "set" of sounds in the settings menu (or use the selected default that opens with the app). If the set is a pitched instrument then it loads as notes. If the set is noisy, it then loads as various sounds to toggle between in the round. You can then toggle to the "timbre" layer, which allows you to apply filters, adjust envelope, etc.

**Comment by starakaj** [comment]
This is also, technically, implemented. Probably it would be best to split new problems into new tickets.
