### ISSUE TITLE
Better indicator for rotations

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#191]

**Comment by starakaj** [comment]
I actually kind of hate the current one and think it's a bit hard to see. Working on a fix.

**Comment by starakaj** [comment]
Okay, I think I've made this a bit easier to see at all times. Let me know what you think...

**Comment by mearabai** [comment]
Wait, did you get rid of the triangle that was popping up under your thumb to help orient during rotation? I'm not seeing it in the latest...

**Comment by starakaj** [comment]
I messed it up in a stupid way. I'll fix it.

**Comment by starakaj** [comment]
K, this should be more or less fixed

**Comment by mearabai** [comment]
Looks good! I think I'd want to make a few cosmetic changes once we skin everything but functionally this is definitely working. Closing until some tester makes us change it.
