### ISSUE TITLE
Onset relationships maintained during pulse changes?

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#196]
Do we want onsets to maintain the same distribution/evenness when we change pulses (as opposed to the current model which partially preserves inter-onset intervals but pins them to one point on the circle)? I'm kind of thinking yes, although I could possibly be convinced otherwise with a water-tight argument.

**Comment by starakaj** [comment]
I think you're for sure right about this. It's something that is actually supported in code, but I turned off to check on something else. I'll un-break it asap

**Comment by mearabai** [comment]
Cool. It would be great to get this unbroken sooner rather than later for ignite filming. Danke!

**Comment by starakaj** [comment]
| I shall move it to a place of maximum priority |

**Comment by mearabai** [comment]
| How did you know that I meant that in the most earnest and non-nagging
way? I almost added something like, 'I am not being passive
aggressive/facetious' to my original comment. In a moment of mental
infirmity I forgot all about | | ! |

On Mon, Jan 12, 2015 at 7:27 PM, Sam Tarakajian <notifications@github.com>
wrote:

> | I shall move it to a place of maximum priority |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/196#issuecomment-69690333>.
>



-- 
http://www.mearaoreilly.com

**Comment by starakaj** [comment]
This should be done, cheggit

**Comment by mearabai** [comment]
This looking real good ya!
