### ISSUE TITLE
Icons for scale/modes?

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#197]
Do we use abbreviations or symbols for pentatonic, major, minor, chromatic?

**Comment by mearabai** [comment]
I'm gonna go ahead and cry Uncle on this: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.vuojddllz6zi

**Comment by starakaj** [comment]
I see you're back on the job...

**Comment by mearabai** [comment]
I think the ones you've made are good for now, I'll keep cracking on them to see if I can come up with something better tho if we decide to keep this interaction pattern.

**Comment by mearabai** [comment]
I made another pass and wrote some more thoughts here: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.a4v9s7k0kn50

**Comment by starakaj** [comment]
Check out the latest master, I think you'll like it.

**Comment by mearabai** [comment]
Making a new ticket for the current paradigm
