### ISSUE TITLE
Transition and animations for atomic actions?

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#199]
I think it would be really helpful to thinking about animating the transitions of atomic actions--flipping over the center axis is often really hard to perceive without a line of symmetry going down the middle. Maybe when you hit the bracelet/flip button the axis appears, (maybe even along with a ghost of the old shape), and then slowly fades? I think I can probably find a more obvious flip to demonstrate for the ignite talk, but I realized when trying to document it that it's really hard to see most of the time...

**Comment by starakaj** [comment]
We've got individual tickets for this, so I'm going to close this one
