### ISSUE TITLE
Re-design web page for mobile

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#201]
Currently all smashed up together in iphone view. I need to make a drawing to send Nimmo so that it no longer looks like this:

![uploads/023ac6cc-44e5-4956-874b-37801c19b0e0/photo (19).PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F023ac6cc-44e5-4956-874b-37801c19b0e0%2Fphoto+%2819%29.PNG)

**Comment by mearabai** [comment]
Alllllmost done. Nimmo is currently removing the top right menu (it's redundant with the bottom one and too pesky to make work on mobile for the budget we want).

**Comment by mearabai** [comment]
It's done!

**Comment by starakaj** [comment]
Looking hella fly. Now I want to see people tweeting about this shit.
