### ISSUE TITLE
Add a thin dotted center line to the flip animation

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#202]
| As discussed yesterday |

**Comment by mearabai** [comment]
Also temporarily ghosting in the previous necklace might be good too?

**Comment by starakaj** [comment]
You can check this one out now. Personally, I think the little dotted line is a bit overkill, but maybe you have some style suggestions that would make it nicer.

**Comment by mearabai** [comment]
I definitely think the line could be a lot thinner, like a delicate whisker--right now it is a little overpowering/distracting. I also wonder if it should be the same color as the necklace? Let's try thinner and white first to see if that improves things tho?

**Comment by starakaj** [comment]
Yeah, Let's look at it when you get in, I think that will be faster

-S

**Comment by mearabai** [comment]
Sounds good.

On Fri, Jan 16, 2015 at 11:49 AM, Sam Tarakajian <notifications@github.com>
wrote:

> Yeah, Let's look at it when you get in, I think that will be faster
>
> -S
>
> On Fri, Jan 16, 2015 at 11:49 AM, mearabai <notifications@github.com>
> wrote:
>
> > I definitely think the line could be a lot thinner, like a delicate
> > whisker--right now it is a little overpowering/distracting. I also
> wonder
> > if it should be the same color as the necklace? Let's try thinner and
> white
> > first to see if that improves things tho?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/starakaj/rnecklace/issues/202#issuecomment-70311260>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/202#issuecomment-70311381>.
>



-- 
http://www.mearaoreilly.com
