### ISSUE TITLE
Add temporary ghosted version of previous necklace to Shadow animation

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#203]
Also flip?

**Comment by starakaj** [comment]
I think I know what you secretly really want here... I'm investigating

**Comment by starakaj** [comment]
Okay... Take a look at this and let me know what you think

**Comment by mearabai** [comment]
Awesome!! I think this is great. I'm particularly enamored with how the old shape leaves an after image in when it disappears. Do you like it?

**Comment by mearabai** [comment]
Oh wait! I just noticed that there's a tiny snap that happens when the shape moves to the new location--it seems a bit distracting and unnecessary, like something more complex is happening than really is. Want me to make an issue to fix it, or was that intentional for some good reason I'm not thinking of?

**Comment by starakaj** [comment]
No... It's a bug. I'm just not looking forward to fixing it because I'm
lazy. But it should be fixed for sure. On the other hand, something more
complex is happening: we're not creating the actual shadow rhythm, but the
closest we can do with a 34 pulse limit. So...
