### ISSUE TITLE
Can we try thinning the dotted lines in deepness mode?

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#204]
Both the line that traces the path and the dotted lines around the pulses.

**Comment by starakaj** [comment]
Of course. Maybe it's better for us to do this in person--I think that way it will take less time overall

**Comment by starakaj** [comment]
Do you still want to do this? Let's talk when you're in

**Comment by mearabai** [comment]
I'm so into still trying this. Let's give it a go when we're both in the office tomorrow.

**Comment by starakaj** [comment]
Nice. Teamwork.
