### ISSUE TITLE
Make Hop and Jump mode work

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#206]
We've got the sliders, let's make them do something.

**Comment by mearabai** [comment]
If you get a chance before Monday night could you please move the top white carrot up (that appears in hop and jump)? I can't really crop it out of the hop and jump demo and it looks messy.

**Comment by starakaj** [comment]
I'll just get rid of that caret entirely. How about that :)

**Comment by starakaj** [comment]
Check on it now?

**Comment by mearabai** [comment]
Looking good. Closing until we decide whether to refine or trash hop and jump.
