### ISSUE TITLE
Fix evenness slider so that it doesn't hop back to uneven when there are no onsets

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#207]
Currently jumps around a lot along with the onset slider--you should be able to set it to degree of evenness and then change the number of onsets if you wish, no?

**Comment by starakaj** [comment]
Yes, that was super unsettling wasn't it? Check it now, should be better

**Comment by mearabai** [comment]
It still seems to be greying out/freezing at either end of the onset spectrum--I think you should be able to move the evenness slider no matter what so that you can set an evenness target and then add or remove pulses.

**Comment by starakaj** [comment]
Okay, a couple small tweaks and I think I've fixed this, but it bears some testing
