### ISSUE TITLE
Design Timbre interface

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#210]
What do the filters/envelopes do and sound like? What does the interface look like?

**Comment by mearabai** [comment]
Some initial sketches before I go into sound design land:
Paradigm one: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.mc090tj3czd5

Paradigm 2: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.xxvn72wlpmjq

**Comment by starakaj** [comment]
Hmm. So I think paradigm two is interesting, but it also seems a bit complex. I'd rather stick to refining what we've got, as opposed to heading off in this new direction. Having said that I like paradigm one. What's the center field of the sample picker for?

**Comment by mearabai** [comment]
I'll work on a drawing for how to integrate the panner, I think the current design you made for attack/velocity is really cool.

**Comment by mearabai** [comment]
Actually I'm closing this issue, it's too vague to keep track of in the line-up
