### ISSUE TITLE
How do you switch between scale modes?

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#211]
Design ui for switching between Major, Minor, Chromatic, and Pentatonic.

**Comment by mearabai** [comment]
Monday Meeting Minutes = we're going to try adding a vertical left swipe with current scale mode text displayed in the usual top spot/text display area. Icing is having some sort of right side display that pops up when you touch left, showing your options. I think we should leave that for later tho, I'm not totally sold on it.

**Comment by starakaj** [comment]
Dnoe, check it. I did it a way that you may not be in love with, but we can refine it from here.

**Comment by mearabai** [comment]
I mostly responded to this in #235, but I'll re-iterate a bit: I think the vertical side text is not useful (and distracting), especially on the left side. If you still feel strongly about testing the idea where they all pop up as a map on the right side when you touch down left I'm open to it, but I mostly just think we should keep all text in the top area and make it easier to switch back and forth between scale modes with a swipe (not having to move a marker from dock to dock).

**Comment by starakaj** [comment]
Just so you know, this is nice and buttery and feels very swipe-y on non iPhone 4

**Comment by mearabai** [comment]
I've been working on some very primitive icons. Let me know if you like this direction at all? It would be good to have at least something that's not vertical text for Beta: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.z9fw3qxdbqep

**Comment by starakaj** [comment]
Just so I have the context right, these would go on the left side, replacing the text that currently reads "pentatonic, minor, major, chromatic" ? These are going to be pretty small. Do you think that these are going to be differentiable at that scale, especially major/minor?

**Comment by mearabai** [comment]
I'm not proposing that we use these, I was just testing out trying to represent the info in the round as icons. The finished ones will obviously be more distinct, I'm just not entirely sure how I'm going to do that yet...It is such a small space, I really am hesitant to use icons. Wanna try to ruler idea? Ticks on the left side,when you touch down left modes pop up right, current mode pops up in top text area?

**Comment by starakaj** [comment]
That seems kind of overcomplicated to me. We can chat about it further if you like, but I feel like we can come up with icons that convey meaning reasonably well. Further, seeing as there are only four choices, I don't feel like the icons need to be too too strong.

**Comment by mearabai** [comment]
Closing this for now.
