### ISSUE TITLE
Refine Octave Interaction

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#212]
Is the current stripe model working? How can it be better?
1)  I'm already wondering if we can drag octave stripes as well as stepping through them with the arrow buttons--feels more fun.

**Comment by mearabai** [comment]
How about placing them vertically along the right side? They can still go away when changing scale modes if we want to show a map of possible scales there. I made a quick drawing here: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.wsr4cjlivppe

**Comment by starakaj** [comment]
I actually kind of like it. Can they be much closer together and centered? Also, bigger?
