### ISSUE TITLE
Add octave number changes to pop-up text menu

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#213]
Whenever you change octaves, the octave number should pop up in that handy text area we have going at the top.

**Comment by mearabai** [comment]
Also, can we add drag-ability to octaves? (Where you can still step through with the side arrows, but also swipe on the note to change octave). If you agree I can make a separate ticket for that. I think having just the arrows for octaves is a little wooden feeling.

**Comment by starakaj** [comment]
A ticket exists for this one already, I think. #232 ? Either way I'm on it.

**Comment by mearabai** [comment]
Yis
