### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#222]
Eventually this will also include sample and timbre settings too, when we have them.

**Comment by starakaj** [comment]
Okay. Check this out. It's possible to save and restore, but you can't delete, rearrange, search or sort. Nor does the current document register "dirtiness", so if you go to make a new document and there are changes, the app's all like "Okay man, I guess you know what you want"

**Comment by starakaj** [comment]
That being said, still think we should show some people.

**Comment by mearabai** [comment]
Ya, we don't gotta provide flawless saving rn, I agree. We can test the polished version in Beta 2
