### ISSUE TITLE
A swipe across the doc causes necklaces to be synced in their pulse count

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#230]
I'm assuming this means the selector bar just extends to be underneath all necklaces. How is it undone? I'm thinking a left to right swipe links everything, right to left un-links?

**Comment by starakaj** [comment]
Give this a try, see how you like it

**Comment by mearabai** [comment]
This is so so awesome! I think it's the best thing since bread and jam. Do you like it? Closing because I'm assuming you do.

**Comment by starakaj** [comment]
Dude. I love it. I'm so, so happy with it. Great idea!

-S
