### ISSUE TITLE
A vertical left side swipe changes scale mode

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#235]
The name of the current mode should be temporarily displayed in the top text area (can we agree on a name for that zone? I keep trying to call it something new each time because I'm a random name generating bot). Icing is showing a map of scale modes on the right side of the screen when you touch left.

**Comment by starakaj** [comment]
Okay. This is working now, as per the name of the ticket. I'll add a new one specific to the description, though.

**Comment by mearabai** [comment]
This is really exciting. I think that the swipe should be less sticky though, and the modes should animate back and forth really easily (as the pulse changes do). I'd love to test out flashing the current mode name in the top text area when ever you touch down left in pitch mode--I think that might be all we need if it's really easy to switch between things (and there are only 4 things). I'll write a ticket for this if there isn't one already.
