### ISSUE TITLE
Beta testing guide

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#237]

**Comment by starakaj** [comment]
Probably can be basically the same as the alpha testing guide, but more thorough and specific. Maybe we even want to consider different use cases?

**Comment by mearabai** [comment]
Here's the guide I sent out to our first round of testers: https://docs.google.com/document/d/1Z5gYm2L4ezQNMmenz4WXjanlHdgSZp6mOpCXYjxOvmE/edit?usp=sharing

**Comment by starakaj** [comment]
Looks good
