### ISSUE TITLE
Fix settings icon so that it doesn't look squished.

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#242]
Doesn't have to be final yet, just not embarrassing. Sam, I'm assuming this is on your end, or is it that I need to export a different file proportion?

**Comment by starakaj** [comment]
This is on my end and I'm embarrassed.

**Comment by starakaj** [comment]
Give this a check. I'm using the asset called ConfigGear in the asset catalogue, which is old. Feel free to replace it if you like.

**Comment by mearabai** [comment]
That'll do for now, I'll add a ticket for myself to replace it. Thanks!
