### ISSUE TITLE
Replace settings icon with outlined version

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#250]

**Comment by mearabai** [comment]
Some drafts here: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.1kymlisoeq7i  I might just choose one for now if you can't be bothered, we can refine later. I just wanted to keep the icons relatively consistent, first impressions are everything you know! -Martha Stewart.

**Comment by starakaj** [comment]
Lol, are all the internal circles the same radius? I've got some crazy optical illusion shit going on with this one. I think I like the middle one most.

**Comment by mearabai** [comment]
Check it

**Comment by starakaj** [comment]
Shweet!

**Comment by starakaj** [comment]
p.s. I'm Meara
