### ISSUE TITLE
Change order of pitch timbre and sample icons

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#260]
I think this will make things a bit clearer

**Comment by starakaj** [comment]
What should the order be ;)

**Comment by mearabai** [comment]
Answer's in the title, dawg.

**Comment by starakaj** [comment]
Cool, will do. But you got to admit, that was a bit cryptic.

**Comment by mearabai** [comment]
|I'm really sorry, you're totally right|. I fully added some sass right on top of my crypt, what a jerk.

**Comment by starakaj** [comment]
Done.
