### ISSUE TITLE
Re-design/add new algorithmic icon to toggle between (bjorklund vs. deep)

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#261]
Is there currently a spot for me to drop this, or do you need to make one?

**Comment by starakaj** [comment]
Ummm.... There's no way for you to make it a toggle... but if you look in the media.xcassets file you'll see an image set called Euclidean and one called Deep. These are the ones you should replace if you want to change the icons.

**Comment by mearabai** [comment]
Check it! The new Euclidean icon now clashes with the atomic icon, but I'm not so fond of that thing anyway...

**Comment by starakaj** [comment]
Cool, lukes great.
