### ISSUE TITLE
Convert 808 samples into AU biz

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#262]

**Comment by mearabai** [comment]
I think this worked, want to build and test the 808 samples on your phone? Any I should get rid of right now? The low bass sounds killer in headphones, not so much on iphone speaker...I'm inclined to leave it in and tell people to play around with headphones at least some of the time?

**Comment by starakaj** [comment]
I say fuck it, leave it in. As long as we can actually use these samples. That's something to consider: most of the samples we're using right now I don't think we can actually use. All the drum kits come from Live, as does the piano. Pretty sure the Kalimba comes from freesound, so at least there's that. Anyway, the 808 is working swell, so I'm ready to close out this ticket. Well done navigating the AUPreset nightmare!

**Comment by mearabai** [comment]
It's a good question. I got the 808 samples from this site:
http://smd-records.com/tr808/?page_id=14 and he says to use freely, but I
don't know if that extends to use in an app/if Roland technically owns
these sounds?? It's the same with the Rhythm Ace samples I found, although
that's a less famous drum machine. Ah legal biz. In any case I think we
should definitely emulate an 808 if we can't use the thing itself, among
other sets....

On Wed, Feb 4, 2015 at 9:26 AM, Sam Tarakajian <notifications@github.com>
wrote:

> Assigned #262 <https://github.com/starakaj/rnecklace/issues/262> to
> @mearabai <https://github.com/mearabai>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/262#event-230194264>.
>



-- 
http://www.mearaoreilly.com
