### ISSUE TITLE
Drive Sam crazy by coming up with a really good brand new idea that he might not like.

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#265]
Mission accomplished? Hear me out, I beg of you: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.l1dfi6rew1na

**Comment by starakaj** [comment]
Definitely something worth investigating after 1.0, in my opinion.
