### ISSUE TITLE
Tempo and atomic menus should close when you rotate or tap away (excepting undo/clear)

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#268]

**Comment by starakaj** [comment]
Too easy :)

**Comment by mearabai** [comment]
I'm not getting atomic actions going away completely, they just go away when your finger is down? I'm also getting Bjorklund being put away whenever you rotate, which shouldn't happen--you should be able to rotate in Bjorklund mode.

**Comment by mearabai** [comment]
You then also have to tap the algorithm icon twice in order to get back to Bjorklund for some reason?

**Comment by starakaj** [comment]
Should be fixed now, give it a check

**Comment by mearabai** [comment]
Bjorklund now comes back after rotations, you no longer have to tap on the algorithm icon twice. Dope.
