### ISSUE TITLE
When changing pulses in Bjorklund mode it should snap back to the sliders view upon lifting your finger

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#269]

**Comment by mearabai** [comment]
Please forgive my [2am I'm about to go to sleep but couldn't help making a few more tickets] grammar.

**Comment by starakaj** [comment]
K it fixed.

**Comment by mearabai** [comment]
Not fixed?

**Comment by starakaj** [comment]
Yeah, wtf?

**Comment by starakaj** [comment]
What about now though?

**Comment by mearabai** [comment]
Yi boi! I'm now getting a weird thing where almost a third of the time touching left doesn't change pulses though. Maybe it's just an iphone 4 thing? Want me to make a separate ticket?

**Comment by starakaj** [comment]
Nah

**Comment by starakaj** [comment]
Chekked nau thø

**Comment by mearabai** [comment]
Yis!
