### ISSUE TITLE
search saved documents

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#276]

**Comment by mearabai** [comment]
Do you mean sort by tag, as opposed to manually?

**Comment by starakaj** [comment]
Tag? I just mean like have a search bar with their names in it.

**Comment by mearabai** [comment]
I truly have no idea what I was thinking when I first interpreted this, or what I meant when I said the above. Sorry pal!

**Comment by starakaj** [comment]
check check checkit

**Comment by mearabai** [comment]
Me and my geriatric phone are going to take your word for it.
