### ISSUE TITLE
Tapping the current necklace in the necklace dock should close pitch menu?

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#279]
I think we had it this way for ipad, and it made it a lot easier to navigate/edit necklaces--just as opening a new necklace opens it in pulse view (rather than pitch), so should tapping the same necklace.

**Comment by starakaj** [comment]
Easy enough

**Comment by starakaj** [comment]
Like this?

**Comment by mearabai** [comment]
Ye dog. I just think it's so much more friendly that way.
