### ISSUE TITLE
We need some way to convey that pitch menu edits noisy samples.

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#282]
When picking a noisy set it needs to be clear that you can choose the particular sample by clicking on the pitch menu again. It is currently completely unclear as to why you would select the pitch menu/note icon to edit drums. Can the pitch (note) icon switch to something else once you've selected a noisy sample set? I'd love to at least test a stand-in for this, unless you have another idea as to how to address this problem...

**Comment by starakaj** [comment]
It would be pretty easy to switch to a different icon, sure. How about we use the old sample icon for now?

**Comment by mearabai** [comment]
I can make a new one and put it in there, wanna let me know where to put it
when you've made the spot, if it's not obvious?

On Wed, Feb 4, 2015 at 10:41 AM, Sam Tarakajian <notifications@github.com>
wrote:

> It would be pretty easy to switch to a different icon, sure. How about we
> use the old sample icon for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/282#issuecomment-72912518>.
>



-- 
http://www.mearaoreilly.com

**Comment by starakaj** [comment]
Sure. Check the most recent push, you'll see that I'm using a new media asset called "Audio" to represent the noisy equivalent to the two little notes.

**Comment by mearabai** [comment]
Cool, thanks!
