### ISSUE TITLE
Opening Atomic menu causes center pitch menu dot to travel up the screen?!

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#284]
Actually, the tempo menu does this too...

**Comment by mearabai** [comment]
Also, fwiw hitting the algorithm button also makes the center button jump up and then re-settle down inside of the smaller Bjorklund necklace. I'm assuming the problem is somehow a function of that?

**Comment by starakaj** [comment]
Yeah. Looks cool, right? But seriously that's not right, is it?

**Comment by starakaj** [comment]
aight, should be good.

**Comment by mearabai** [comment]
Ficksed
