### ISSUE TITLE
Re-do icon interferes with necklace

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#285]
Can we move it a touch to the left?

**Comment by starakaj** [comment]
Shure!

**Comment by starakaj** [comment]
What about now? If you'd like to play with this yourself, you can edit RNAppConfig, specifically the parameters RNDockViewController_UndoRedoSpacing and RNDockViewController_RedoYOffset

**Comment by mearabai** [comment]
Much better, although when the pulse next to it expands it buts up against. I'll take a look. This isn't urgent, just should be addressed before launch.
