### ISSUE TITLE
Fix Super Bug in noisy sample mode

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#287]
Sorry to be the bearer of bad news, but there seems to be a pretty bad bug when you try to switch between noisy percussion sets (see photo). It looks like the counting of sections gets all thrown off and the wedges get drawn wrong. The bug also messes with the sample audio, depending on the order of sets you switch between. It seems like it's trying to spread the samples over 12 steps no matter how many there are in the set?
![uploads/be895e6e-9dd0-40eb-96f3-80d219082159/photo (21).PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe895e6e-9dd0-40eb-96f3-80d219082159%2Fphoto+%2821%29.PNG)

**Comment by starakaj** [comment]
That is, most definitely, not correct :)

**Comment by starakaj** [comment]
Should be fixed as of the latest. Looks like a crazy disgusting bug, actually not that tricky a fix.

**Comment by mearabai** [comment]
Ya!
