### ISSUE TITLE
During copy/paste, line animation should switch to be curved sooner

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#288]
We were thinking around when the thumb gets to the mute button? Let's try that.

**Comment by starakaj** [comment]
check check check it

**Comment by mearabai** [comment]
I actually think the switch should happen even sooner, like almost as soon as you've crossed over the mute button of the necklace you're leaving.That and/or the transition should be a lot smoother/both lines should be the same color? Maybe we should talk more about this when I get in?

**Comment by starakaj** [comment]
I'm not quite sure what you mean, so let's talk when you get in.

**Comment by starakaj** [comment]
This just got a bit... pervy might be the word. You should have a look.

**Comment by starakaj** [comment]
Nice and pervy, huh?

**Comment by mearabai** [comment]
That is the pinnacle of pervy. So good!!
