### ISSUE TITLE
When you touch down left,  2X and  2/ icons pop up on the right

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#290]
This allows you to quickly jump to multiples or divisions of the current pulse count.

**Comment by starakaj** [comment]
hmm hmm hmm

**Comment by starakaj** [comment]
Okay, what do you think?

**Comment by mearabai** [comment]
Cooooooooool. I think the text should be a bit more separated from the arrows, but we can also address that in the skin pass if you'd rather punt it for now.

**Comment by starakaj** [comment]
Skinnit
