### ISSUE TITLE
Investigate possibility of showing sample name rather than midi number when you touch down on sample.

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#292]
In noisy percussion sets it currently shows the midi number, which is confusing.

**Comment by starakaj** [comment]
This was actually super easy. Don't know why old sam bitched about it. Probably not enough coffee

**Comment by mearabai** [comment]
So super fly. Now I have to go back and name all the layers in my au presets. Thanks Sam, thanks a lot.
