### ISSUE TITLE
Address distortion that occurs when notes occur simultaneously

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#305]
Can we start playing around with this now, or do we want to wait until we have all of the sounds?

**Comment by starakaj** [comment]
Cool, I think we can just sort this out with a little bit of compression

**Comment by starakaj** [comment]
Okay. This bug is absolute perfect proof, if proof were needed, that my ability to estimate bug difficulty is dangerously underdeveloped

**Comment by mearabai** [comment]
I think it's sounding a lot better? Hard to tell without ABing...Closing for now.
