### ISSUE TITLE
Make a manually pitched sample test

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#310]
By this I mean do the most agonizingly mundane and fiddly task of adding all pitches by hand to one preset to make octaves sound better.

**Comment by starakaj** [comment]
Ho boy. Doing god's work, that's for sure.

**Comment by mearabai** [comment]
K, so I think it's sadly evident that it sounds better when we manually add octave samples rather than letting apple pitch shift them. Take a listen to Bell and Bell2 at various octaves and tell me what you think though? I guess we could do it on a case by case basis if a sample is getting particularly crunched in the higher ranges, etc. There's also a bunch of random samples at various pitch ranges in Ocda773 for you to play around with.

**Comment by starakaj** [comment]
These do sound much, much better. We might be able to get away without sampling each and every note, though. Two per octave? Or maybe it's better to just go for it (not too much more painful to tweek 60 samples versus 20)

**Comment by starakaj** [comment]
Either way, your hard work is acknowledged and appreciated
