### ISSUE TITLE
Make all sample presets compatible with new envelope paradigm

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#315]

**Comment by mearabai** [comment]
Ok, I did a test and I'm not sure it's working/that I did it right? I'm hearing a volume shift but no envelope change. Wanna take a look/listen? The preset is called Sound2Test.

**Comment by starakaj** [comment]
Hey-o,

It looks like Layer 1 was configured correctly, but not Layer 2. Did I
mention that it actually has to be setup for each layer? Hopefully it's not
deliberately saving it incorrectly or something like that.

-S

**Comment by mearabai** [comment]
Ahem. I did know that, but somehow didn't know that at 1am when I was stubbornly trying to make one work because I'd just spent hours formatting the samples. This is clearly not a late-night task.
