### ISSUE TITLE
Fix UI for MIDI mode

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#318]

**Comment by starakaj** [comment]
Should be possible to pick MIDI channel (currently it ain't)

**Comment by starakaj** [comment]
Now it is. 'Nuff said, I guess.

**Comment by mearabai** [comment]
Siiiick. It's currently a bit buggy to pick midi channel (takes a few tries to select one).  Maybe just an iphone 4 thang?!

**Comment by starakaj** [comment]
Nope, it's straight buggy. I'm working on it.

**Comment by mearabai** [comment]
Looking good now
