### ISSUE TITLE
Hey! This is your friend Meara here. Is there going to be any way to edit the length of a sample?

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#320]
Can we still do this please? I think it would make the envelope function that much more awesome and worthwhile.

**Comment by starakaj** [comment]
Tone here suggests that you think this is really going to piss me off, but I'm not opposed to this idea. How do you feel about controlling envelope along a single dimension, like we had it before? So as you drag left-right, the envelope moves from short attack short length, through to short attack medium length, all the way to long attack long length. I'm proposing this specifically in place of separate controls for attack time and decay time. Yes I know it's fun sometimes to have a long attack and a mega short decay. No it doesn't make me happy to decide against fun. But there it is.

**Comment by starakaj** [comment]
Okay, play with this, let me know what you think.

**Comment by mearabai** [comment]
I definitely think that we should at least be able to separate attack and length if we aren't going to have a full ASDR, but I'm willing to test the current version out on users first before I get all T-Mearasaurus.

**Comment by mearabai** [comment]
Closing this particular issue for now.
