### ISSUE TITLE
Write Zach and Patrick about advice for app pricing

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#321]

**Comment by mearabai** [comment]
Awaiting response.

**Comment by starakaj** [comment]
Still?

**Comment by mearabai** [comment]
I wrote Zach, still haven't heard back (that's why it's idling in the review section under my name). I think he was out of town, hoping to hear from him today. I'm gonna wait until we send the beta to Patrick to ask about pricing--he'll have a better idea once it's in his hands.

**Comment by mearabai** [comment]
K. Zach hasn't written back yet, I suspect I'll have to hunt him down in person. I'll ask Patrick about this stuff when we send him the Beta, he already wrote back with his UDID.
