### ISSUE TITLE
Work on Sam's Baby samples

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#323]
Or forever hold yr peace.

**Comment by starakaj** [comment]
Working on a nice clean guitar right the now

**Comment by starakaj** [comment]
Guitar and piano are back in (piano shouldn't be crashing anymore) Give then a spin?

**Comment by mearabai** [comment]
We talked about this in person, but they definitely need more mastering so that they don't dominate other sounds when we eventually enable sounds individual necklaces. I have to admit I'm not tooootally sold on them yet in general.

**Comment by starakaj** [comment]
This guy.
