### ISSUE TITLE
Test out a variety of operator sounds, decide which ones to do the painful audiophile treatment on and keep

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#327]

**Comment by mearabai** [comment]
I pushed a bunch of test samples that haven't been made into presets yet, there are two different octave samples for each sound (C2 and C3). Once I figure out how to correctly configure the envelope biz (see #315) I'll make them into rough presets so we can edit them down to a choice few before I do a manual pitch shift for the finalists.

**Comment by mearabai** [comment]
These are now presets configured for envelope control. They need to be compressed, they aren't yet optimized for octaves and some of them are really similar on purpose so we can choose between them.

**Comment by starakaj** [comment]
K, looks good

**Comment by mearabai** [comment]
Any favs? Any clunkers or sounds you think could be good if they were
improved?

On Fri, Feb 13, 2015 at 11:17 AM, Sam Tarakajian <notifications@github.com>
wrote:

> Closed #327 <https://github.com/starakaj/rnecklace/issues/327>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/327#event-235603383>.
>



-- 
http://www.mearaoreilly.com
