### ISSUE TITLE
Make timbre controls save to the document

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#332]

**Comment by starakaj** [comment]
Should be working now

**Comment by mearabai** [comment]
Hmmmm, looks like timbre is saving, but pulses and pitches weren't??

**Comment by starakaj** [comment]
Woah.

**Comment by starakaj** [comment]
Nice, | good find |

**Comment by mearabai** [comment]
I'm getting a bunch of freezes when I try to navigate between saved copies of various envelope settings?

**Comment by mearabai** [comment]
I think it's fine now...
