### ISSUE TITLE
New icons for sample and timbre view

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#334]
Maybe tweak pitch view?

**Comment by mearabai** [comment]
Given that sample view is deemed fine until more people complain, here are some nascent passes at envelope icons: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.a1f0t7a1tuh6

**Comment by starakaj** [comment]
I like the guy on the bottom right that looks like two mountains. All the sample ones look the same to me, but good the same.

**Comment by mearabai** [comment]
Lol, the sample ones look all the same because they are the same. I'm
holding off on re-designing those until we know it's necessary. Glad you
like the envelope icon tho. Do you like like it, or should I keep
iterating? It needs to be cleaned up a bit either way.

On Fri, Feb 13, 2015 at 11:17 AM, Sam Tarakajian <notifications@github.com>
wrote:

> Assigned #334 <https://github.com/starakaj/rnecklace/issues/334> to
> @mearabai <https://github.com/mearabai>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/334#event-235603210>.
>



-- 
http://www.mearaoreilly.com

**Comment by mearabai** [comment]
I'm trying out the idea of replacing the tape icon with a book, I like the square dimensions more in context: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.1yu8eptw1jh3  What do you think?

**Comment by starakaj** [comment]
I prefer the tape but not by much. If you'd rather the book then I'm easy. The other icons look great.

**Comment by mearabai** [comment]
I'm on the fence (the other way). I'll export versions of both and we can swap them if one of us has a convincing argument either way.
