### ISSUE TITLE
Change order of settings menu

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#350]
I think saving and loading sessions are more top level than midi stuff and should come first. Do you agree? Wonderful. Perhaps it should go: saving and retrieval, help, midi? Or do you think help and about should be at the bottom?

**Comment by starakaj** [comment]
I think help and about should be at the bottom, otherwise I agree completely

**Comment by starakaj** [comment]
What about now though? :)

**Comment by mearabai** [comment]
Bellissimo
