### ISSUE TITLE
Defer to isaiah, the impartial third party, about the cartouche for pitch timbre sample

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#352]

**Comment by mearabai** [comment]
He said he'll take a look tonight.

**Comment by mearabai** [comment]
The ballot is counted and Isaiah thinks we should do something like this: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.1yu8eptw1jh3

**Comment by starakaj** [comment]
Oh man. So I have to say that I think this particular choice is actually the worst of both worlds. But I said we'd defer, so I defer. Would you still be down to go with your original design idea, which I actually prefer?

**Comment by mearabai** [comment]
Which one? Where the current icon is bolded, or the one with the floating colored box?

**Comment by starakaj** [comment]
Floating color box.
