### ISSUE TITLE
Add clock icons for when app is doing MIDI clock stuff

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#353]

**Comment by starakaj** [comment]
Here's what I did:
1. When you turn on MIDI clock out, you'll see a little clock next to the play/pause button, so you know your transport is being sent to the world.
2. When you turn on external clock sync, the play pause icon gets turned into a clock
3. Tapping on that clock lets you know why play/pause isn't working.

Thoughts?

**Comment by mearabai** [comment]
As we discussed, I love the play icon turning into a midi clock when you're in external clock sync.  I'm still working on how to make the second function look better, I'll make myself a ticket for it.
