### ISSUE TITLE
Add panning to envelope view

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#354]
Of course this only shows up when headphone jack is engaged. Do you want me to make a design before you implement, or do you already have an idea of how you want to do it?

**Comment by starakaj** [comment]
No need to wait on a design, I'm on it.

-S

**Comment by starakaj** [comment]
Check check it

**Comment by mearabai** [comment]
I can't even tell you how excited I am about this.

**Comment by starakaj** [comment]
:)
