### ISSUE TITLE
Move octave buttons over to the far right of the screen with a big touch zone to the left of them

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#356]
Want me to make some halved arrows for that? Ok I will.

**Comment by mearabai** [comment]
I'm thinking the side arrows actually look weird. I think it's better if they are less stretched but still centered.

**Comment by starakaj** [comment]
Sounds good to me

**Comment by starakaj** [comment]
Want to draw me some triangles?

**Comment by mearabai** [comment]
Just pushed some octave triangles, should be placed already?
