### ISSUE TITLE
Switch label for bjorklund onset slider to say "beat count" instead of "onset count"

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#358]
Onsets are for deep nerds like us. I don't think the world is quite ready for that yet.

**Comment by starakaj** [comment]
Beat's not the right word either though, is it? Event count? Note count?

**Comment by mearabai** [comment]
I dunno! I guess note count? I kind of still prefer beat but don't really love either one.

**Comment by mearabai** [comment]
Wanna just try note count and see if people get it?

**Comment by starakaj** [comment]
Sure

**Comment by starakaj** [comment]
Feast your eyes
