### ISSUE TITLE
Refine slider design

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#359]
Here's some variations on what's there now: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.wzqwjaq1taxc

**Comment by starakaj** [comment]
Last one is my favorite by far. You?

**Comment by mearabai** [comment]
Let's try it. It looks like the slider asset is broken down into three parts, I'm taking that to mean I should export the slider line, fill, and handle separately?

**Comment by mearabai** [comment]
By line and fill I obviously mean minimum and maximum, lol.

**Comment by starakaj** [comment]
And now?

**Comment by mearabai** [comment]
I think it's looking really great but the stroke is still too thick--everything else is two points (pixels?) and we shouldn't break that just for sliders. If you really want to go through together and select things to make various weights we can, but I think it looks better when it's all consistent.

**Comment by starakaj** [comment]
Check it now

**Comment by mearabai** [comment]
Looking good!
