### ISSUE TITLE
Make undo work for Bjorklund mode

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#362]
When in Bjorklund mode the undo button currently only affects other previous actions (not evenness percentage, or onset count sliders).

**Comment by starakaj** [comment]
Lol oversight. I'll get it

**Comment by starakaj** [comment]
Chekkit

**Comment by mearabai** [comment]
Great! I'm thinking maybe the text should reflect the new value instead, maybe saying something like "reset to #$ value" so that you know what you're undoing to?

**Comment by starakaj** [comment]
Should be good now

**Comment by mearabai** [comment]
Sweeet!
