### ISSUE TITLE
Undoing copy/paste doesn't include pitch/color

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#363]

**Comment by starakaj** [comment]
This will require a slightly larger amount of work than I'd like, but it shouldn't be too bad.

**Comment by starakaj** [comment]
It turns out that, though this requires more work than one might think, it requires less than I apparently thought it would 28 minutes ago.

**Comment by starakaj** [comment]
Check it now though

**Comment by mearabai** [comment]
Jåä!
