### ISSUE TITLE
Apply color corrections

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#365]

**Comment by mearabai** [comment]
Here's a rough screenshot of the colors I'm going to change: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.yxwa8i8rf7hp

**Comment by mearabai** [comment]
HSB Values (color names are only wildly approximate):

Yellow  51 89 100
Yellow-Orange  34 93 100
Orange 12 87 100
Red 357 87 100
Magenta 335 73 100
Pink 291 71 100
Purple  261 71 100
Purple-Blue 226 63 100
Blue  193 89 100
Blue-Green 176 100 99
Green 130 69 87
Green-Yellow 75 78 98

**Comment by mearabai** [comment]
Hey, what's the meaning of these two hue values separated by / ?  Are they for inner geometry versus pulse hue?
![uploads/563e66dd-aede-4621-8a8b-f5c00c996f96/Screen Shot 2015-02-16 at 12.54.09 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F563e66dd-aede-4621-8a8b-f5c00c996f96%2FScreen+Shot+2015-02-16+at+12.54.09+AM.png)

**Comment by starakaj** [comment]
Nah, that's just division. So the hue for the second one is (1.0 / 12.0), or 0.08333

**Comment by mearabai** [comment]
I just added the new colors, but they still aren't looking right...There must be something else I'm missing? Also, I'm assuming we are programmatically selecting different colors for different modes, can we customize that? With the new color palette for example the defaults in Pentatonic mode don't look so hot together, etc.

**Comment by mearabai** [comment]
I'm gonna re-work these to optimize for looking good in pentatonic mode first, as well as see if I can't adjust them to look more like the photoshop swatches...

**Comment by mearabai** [comment]
I'm gonna try rotating to start on another color to see if Pentatonic looks better that way. Isaiah pointed out that in order to have 12 perceptually distinct colors you can't solve for 5 first and then divide inbetween. If different rotations don't work I'll go back to the drawing board...

**Comment by mearabai** [comment]
I pushed two different variations, starting on orange and magenta. I'm mega not a fan and I'm starting to think that color should represent number of steps in a scale instead of specific pitch. I think having colors that look harmonious together in each mode, and having each mode look distinct is more important than each note always being the same color. Let's talk tomorrow...

**Comment by starakaj** [comment]
Sure. Though I should say that I think color, while super important, is something that we can play with during beta.

**Comment by mearabai** [comment]
I didn't revert this, I'm fine if you think the current colors look bad together rn and you want to until we make the above changes.

**Comment by starakaj** [comment]
That is exactly how I feel :)
