### ISSUE TITLE
Clean up clear icon

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#367]

**Comment by mearabai** [comment]
It's currently a thinner stroke than everything else, and the cross-line is a bit off.

**Comment by mearabai** [comment]
See homescreen icons: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.2gpa5kf3jmx5

**Comment by starakaj** [comment]
Wow, looks great.

**Comment by starakaj** [comment]
Make me some assets! (please)

**Comment by mearabai** [comment]
Have a looksy
