### ISSUE TITLE
Re-make Play/Pause icon

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#368]

**Comment by mearabai** [comment]
See homescreen icons: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.2gpa5kf3jmx5

**Comment by starakaj** [comment]
Looks great.

**Comment by mearabai** [comment]
Play is in there, I'm gonna tweak pause and push that in a sec. How do you feel about having the play icon load with the app but quickly switch to the pause icon once the app starts going? I feel like that solves the problem of wanting a good first presentation while also demonstrating that important basic toggle function.

**Comment by mearabai** [comment]
What do you think about this pause icon? Closer? Further apart?
![uploads/246927aa-b130-4751-8d60-7316b39be012/Screen Shot 2015-02-17 at 4.16.15 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F246927aa-b130-4751-8d60-7316b39be012%2FScreen+Shot+2015-02-17+at+4.16.15+PM.png)
