### ISSUE TITLE
Get us some Beta Testers

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#372]

**Comment by mearabai** [comment]
Gathering UDID's here: https://docs.google.com/document/d/1lm4mKglr9AGvJVZDL6zrtDaQ5WsctF5gkjTWwLZAzoo/edit#bookmark=id.wh1nxv1y3vhe

**Comment by mearabai** [comment]
How many do we ideally want? Should I tweet about it and re-label the website to say sign up for beta?

**Comment by starakaj** [comment]
I think up to 20 would be good, but imho more is better. Though I'm
hesitant to make an open call for beta. Let's keep to to people we can
actually bully over email until we absolutely need to open it up further.
BTW, I've tapped the C74 network, as well as a few other people. Hopefully
I'll have snagged some more UDIDs today.

-S

**Comment by mearabai** [comment]
I added two more people to the list: Gabriel Dunne and Eric Rosenbaum, the dude from MIT who made makey makey and a bunch of super awesome music apps (have you seen that singing fingers app?). Gabe never got back about his iOS version, but I'm assuming it's up to date?

**Comment by starakaj** [comment]
Let's roll with it!

**Comment by starakaj** [comment]
Cool. These guys have been added. I made a new ticket about getting these beta testers into a spreadsheet with Name, UDID, Device Type, Email and Notes, btw, since the current doc is getting just a tad unwieldy.
