### ISSUE TITLE
Make new octave arrows

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#373]

**Comment by mearabai** [comment]
I think I like the centered arrows better: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.2cddkc3kv48s

**Comment by starakaj** [comment]
Agreed.

**Comment by mearabai** [comment]
The octave arrows are in the sketch file, but I couldn't see where they should go in xcasset world?

**Comment by mearabai** [comment]
JK, I found it.

**Comment by starakaj** [comment]
Cool!
