### ISSUE TITLE
Size all icons in regards to one another

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#375]
I'm basically making a master sketch for each menu view, with accurate sizes to then export once we've agreed on them.

**Comment by mearabai** [comment]
Screenshots are all here: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.2gpa5kf3jmx5

Once you agree about relative sizes for everything I can begin exporting!

**Comment by starakaj** [comment]
Everything looks dope. Please xport!!
