### ISSUE TITLE
Make top menu icons have the same margin as the bottom navigation dock

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#378]
See: https://docs.google.com/document/d/1mjmomhfpTHilU5UI1XAEeUvNMv0ELiJ8lRJauu_Y5wQ/edit#bookmark=id.2gpa5kf3jmx5

**Comment by starakaj** [comment]
k

**Comment by starakaj** [comment]
Check it?

**Comment by mearabai** [comment]
The spacing looks better to me, but I think the place holder line up top is still too close to the icons and feels wicked cramped--I think it should either be up against the edge, or hovering exactly inbetween the edge and the icon. We can talk about this when I get in if this is unclear.

**Comment by starakaj** [comment]
Probably it will be faster if we do it together, so I'll wait for you to
get here.

-S
