### ISSUE TITLE
Refine pause icon

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#383]

**Comment by mearabai** [comment]
How's this for a pause icon? I closed the other issue already so re-posting:

![uploads/8af7513f-e02e-4368-b05a-762846d48a0f/Screen Shot 2015-02-17 at 4.16.15 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8af7513f-e02e-4368-b05a-762846d48a0f%2FScreen+Shot+2015-02-17+at+4.16.15+PM.png)

**Comment by starakaj** [comment]
Ooof looks great!
