### ISSUE TITLE
Make midi clock icon

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#386]

**Comment by mearabai** [comment]
What size do you want this out, are there any code constraints?

**Comment by mearabai** [comment]
![uploads/bf897ec3-9fa2-4548-b9e5-42d962146ab8/Screen Shot 2015-02-17 at 8.45.59 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbf897ec3-9fa2-4548-b9e5-42d962146ab8%2FScreen+Shot+2015-02-17+at+8.45.59+PM.png)
You ok with this icon? I can change the hands to be more like the one you drew, if you like.

**Comment by starakaj** [comment]
Looks great to me. The size constraints are the same as the other top row
icons: 34 px tall.

**Comment by mearabai** [comment]
I'm assuming the same icon size will work for both sync to external clock
and send midi clock data situations (full size vs. tiny)?

On Tue, Feb 17, 2015 at 8:47 PM, Sam Tarakajian <notifications@github.com>
wrote:

> Looks great to me. The size constraints are the same as the other top row
> icons: 34 px tall.
>
> On Tue, Feb 17, 2015 at 8:46 PM, mearabai <notifications@github.com>
> wrote:
>
> > [image: uploads/bf897ec3-9fa2-4548-b9e5-42d962146ab8/Screen Shot
> > 2015-02-17 at 8.45.59 PM.png]
> > <
> https://camo.githubusercontent.com/6fe4336c45eecdd5039fcc1aea5abfbe08615876/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642e6875626f6172642e636f6d2f75706c6f61647325324662663839376563332d396661322d343534382d623965352d34326439363231343661623825324653637265656e2b53686f742b323031352d30322d31372b61742b382e34352e35392b504d2e706e67
> >
> > You ok with this icon? I can change the hands to be more like the one you
> > drew, if you like.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/starakaj/rnecklace/issues/386#issuecomment-74811525
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/386#issuecomment-74811634>.
>



-- 
http://www.mearaoreilly.com

**Comment by starakaj** [comment]
Should be fine
