### ISSUE TITLE
Tapping a new necklace on the dock inconsistently flashes "one necklace selected"

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#387]
I think that's a bug, but I'm starting to think maybe the text should only flash when you change quantities of necklaces selected (maybe as well as the first time you select a new necklace). Either way it should be consistent.

**Comment by starakaj** [comment]
What about now though?

**Comment by mearabai** [comment]
Now I'm seeing that it never says 1 necklace selected? I think it's important to happen the first time you tap a necklace to give the idea that you can select more than one, I just don't think it should be happening every time you tap a new necklace, ya know?

**Comment by starakaj** [comment]
With respect, I disagree. So the way it works now is this: when you tap on a necklace it says nothing, but if you drag to select two, then drag back to select only one, it says "one necklace selected". I think this is the way to do it: you don't want to be told every time you change necklaces that there's one necklace selected. If we want to tell people that they can select multiple necklaces, Quick Start is the right place.

**Comment by mearabai** [comment]
Like I said, I don't think it should happen all the time. I meant that the very first time you change necklaces it flashes that, as in the first time you open the app. I'm fine to leave it as is and wait for feedback--I'm curious as to whether people will discover it less the way it is now.
