### ISSUE TITLE
Pause and play icons are currently reversed

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#389]

**Comment by mearabai** [comment]
Did you see my note about loading with the play icon but switching to pause once the animation starts? I know it's a small detail, but in terms of first impressions I think it's really important. If not for this version, definitely for the final? What do you think?

**Comment by starakaj** [comment]
I see what you mean. Yeah, we can do that.

**Comment by starakaj** [comment]
Check it now? We can make the play delay longer if it scares people

**Comment by mearabai** [comment]
Goot!
