### ISSUE TITLE
Move Beta Testers to a Google Spreadsheet

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#394]

**Comment by starakaj** [comment]
So we can like actually keep track of them.

**Comment by starakaj** [comment]
Name, UDID, Device Type, Email and Notes would be good stuff to have, I think.

**Comment by mearabai** [comment]
In progress: https://docs.google.com/spreadsheets/d/1qLQBnE99QC1z12IHDWm21VUjMCUfVKkFuN5iPzSbK10/edit?usp=sharing
