### ISSUE TITLE
Collate all beta tester notes into one document

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#400]

**Comment by mearabai** [comment]
All question answers received are now in this document: https://docs.google.com/document/d/1Twr-Rn4LgC6O4sa97P-wt3mUMp63zoq-v51DE5bWEAA/edit?usp=sharing Worth reading through again, I noticed a few more things we might want to address when looking at them all at once.

**Comment by starakaj** [comment]
You are truly doing God's work. Thank you so much!
