### ISSUE TITLE
Decide on final app font

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#407]
Right now I'm thinking Futura, wanna try it? If you're not convinced I can make some samples and we can pick from a few of them...

**Comment by mearabai** [comment]
I think this is the font we should use in the app, it's what's already in our branding on the website: https://www.fontyukle.net/en/Futura+%28Light%29.ttf I haven't tested this particular download out yet, but I'm assuming it's what we need.

**Comment by starakaj** [comment]
I'll see how it looks

**Comment by starakaj** [comment]
I'm going to start with Futura Medium, since it's already included with iOS 8. If it doesn't look right we can go to Futura Light, but we'll have to import it.

**Comment by starakaj** [comment]
Cool it's done. We've made a couple of other tickets for the one or two UI bugs that got caused by the font change, which I'm working on now.
