### ISSUE TITLE
Configure all noisy sample sets for attack control

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#414]

**Comment by mearabai** [comment]
This includes fine-tuning the octave number and testing it with Max before final export so that the sounds don't disappear when you remove the attack

**Comment by mearabai** [comment]
Both 808 and Rhythm Ace are now configured for attack, although I need to go back through and massage the octave numbers so they don't become essentially silent as soon as you take away the attack. I'll do the same to the other drumkits once I re-make them :(

**Comment by mearabai** [comment]
I just made new 909 and C78 presets, so now all versions of current drumkit presets with rough attack and release are pushed. I'm going to go through next and address the individual attack time ranges of samples, right now everything is still at 10 octaves. Take a listen and let me know if you think .5 seconds is good for the release on everything in the noisy percussion realm?

**Comment by starakaj** [comment]
909 seems busted, I'll take a look at it when I get the chance

**Comment by starakaj** [comment]
This is done now, isn't it? What's the status of this ticket?

**Comment by mearabai** [comment]
Some of the sounds still need to be adjusted so they aren't silent when the
attack gets taken away

On Fri, Feb 27, 2015 at 11:54 AM, Sam Tarakajian <notifications@github.com>
wrote:

> This is done now, isn't it? What's the status of this ticket?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/414#issuecomment-76460546>.
>



-- 
http://www.mearaoreilly.com
