### ISSUE TITLE
"Master" sounds for all form factors

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#416]
Current plan: make a compressor that’s only activated when you plug in headphones, or when volume is at full volume. All sounds should be the same level and shouldn't distort/clip on any phone version. For example current sounds do this at top volume on iphone 6.

**Comment by starakaj** [comment]
Done, see how you feel about it. We may need to tweak the numbers just a teense.

**Comment by mearabai** [comment]
As discussed, I think we need to address what happens when sounds happen simultaneously. The overall compression is sounding good now though.
