### ISSUE TITLE
Address Kael's midi note off problem

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#426]
Kael sez: "Only issue is I’m only getting “Note On” events without a corresponding “Note Off” event, so all the notes stay held down which can get a bit overwhelming :P"

**Comment by starakaj** [comment]
I actually can't reproduce this on my end. It's possible that we've fixed this since we last put a beta in Kael's hands, though frankly I doubt it. I'll pump him for some more information

**Comment by starakaj** [comment]
Still can't reproduce. I've written Kael about it, I'll revive this ticket when he gets back to me.
