### ISSUE TITLE
Design first menu for NUX intro

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#437]
Currently is apple default, should be something nicer

**Comment by mearabai** [comment]
Whatever this is, it needs to not be the apple default. A black box similar to the other text menus would be a start.

**Comment by starakaj** [comment]
I'm working on backend changes to make this possible ATM

**Comment by starakaj** [comment]
Before you get too too deep into this, let me do some investigation--it's a very Apple-y widget so we don't have infinite customization powers.

**Comment by starakaj** [comment]
Okay, just sent you a screenie with the results of my findings

**Comment by mearabai** [comment]
This looking so much better, I might want to still tweak it a tiny bit though after I get all of the sound stuff done

Current parameters up for grabs: 
fonts, font size
size of box
corner rounding
border thickness
colors

(not sure if there can be lines separating the buttons)
