### ISSUE TITLE
Making a deep rhythm in evenness mode should cause the top slider to reflect current evenness.

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#438]
I think this could be a really cool feature, to use evenness mode as a measure for deep rhythms, but currently it only accurately reflects the number of onsets you've added, not the evenness. Is this is too hard to do before release I think we should think about disabling deepness while evenness is open.

**Comment by starakaj** [comment]
A super smart idea. Also not hard to do. Also done.

**Comment by mearabai** [comment]
This is great! I think the evenness value and onset count should flash in the text area so you can see what you've just made tho
