### ISSUE TITLE
Address the audio smush/distortion that happens when two notes sound together at most upper volumes

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#440]
As discussed today. If I'm being vague it's because my tired brain forgot the details of what we decided (but at least managed to remember this was an important thing to do). We can re-discuss if you also can't remember?

**Comment by starakaj** [comment]
Take a listen to the most most recent? I made the compressor much more aggressive. Unfortunately there's only so much we can do at those much higher volumes.

**Comment by mearabai** [comment]
I think this is better, although it would be good to AB test it at some point...Closing for now.
