### ISSUE TITLE
Export operator pitched sounds note by note so we don't have to use AU's pitch shift biz and so sounds actually are distinct at upper octaves

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#442]

**Comment by mearabai** [comment]
Note by note samples have been made for all sounds. Now to make them into presets! Oh goody.

**Comment by mearabai** [comment]
Yo, so I re-arranged the marimba preset so that it acurately starts at C1, but it makes the default pitch range (C3) pretty high. I'm guessing we should either set the default to be C2 or decide that we like the high pitched starting sound before I make the rest of the presets. For your comparison, please check out "Marimba with Release" against "Marimba with attack release corre[ct8ave]" (the title gets cut off in the app). These presets are offset by one octave, depending on how they are configured....Let's talk tomorrow, I'm gonna try to tuck in early and get to the office on the earlier side so we can sort this out...Once we make this decision it should be pretty fast to make the rest of the presets using the marimba template, I just didn't want to do everything twice.

**Comment by starakaj** [comment]
Understood. Sorry it's so confusing, the fact of the matter is that all
this C3 and C4 stuff is totally arbitrary and different applications are
free to label them however they want. Actually I agree that calling middle
C C4 makes the most sense--if our app calls middle C C3 then I'm not sure
what old Sam and old Meara were thinking. HA! Actually, I see now what the
issue is: Max/MSP calls middle C C3 and I probably went with that. Well
listen, Max, you're not my real dad, and if scientific notation calls it
C4, then as far as I'm concerned it's C4 (
http://en.wikipedia.org/wiki/C_%28musical_note%29#Middle_C). So I'll make
it C4 in the app.

**Comment by starakaj** [comment]
Yeah, Marimba with attack release corre[ct8ave] (great name!) is definitely
shifted one octave up, so it's playing the note one octave above middle C
as if it were middle C. Again, really sorry for the confusion; as usual all
I can do is blame Max.

**Comment by mearabai** [comment]
So what you're saying is that I should be pitching my sounds starting at C2 in au sampler?

**Comment by starakaj** [comment]
Yes

**Comment by mearabai** [comment]
This was so painful, but surprisingly doable on an airplane (transport I find equally painful).  I hope it was worth it.
