### ISSUE TITLE
Make play and tempo icons smaller so that they perceptually match the rest of the top row

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#447]
It needs to be resized to match the others and it looks like it's a thinner stroke than the rest of the icons?

**Comment by starakaj** [comment]
Yeah, good catch. The atomic transform icon is actually a little wonky as
well. I'm on it.

**Comment by starakaj** [comment]
Take a look at this, I've had my way with it.

**Comment by mearabai** [comment]
Looking much better stroke-wise, but I'm wondering if it's still a bit small? I think we could make both settings and evenness icons a tiny bit bigger

**Comment by mearabai** [comment]
Actually, maybe we keep those icons the same and make play and tempo icons a bit smaller? I got Isaiah to weigh in and that's what he said too...
