### ISSUE TITLE
Get us some dope-a$$ @rhythmnecklace emails

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#461]

**Comment by mearabai** [comment]
Looks like I need to transfer the DNS back to the host in order to set it up, not sure if that will F anything that Nimmo set up. I sent him an e-mail asking as much, waiting to hear back.

**Comment by mearabai** [comment]
Should work in a few hours, let me know if you get an e-mail from me?

**Comment by starakaj** [comment]
Oh fuck yes.
