### ISSUE TITLE
Make the Necklace respond to touches correctly when in Evenness

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#463]

**Comment by mearabai** [comment]
You read my f^$^in' mind.

On Fri, Feb 27, 2015 at 11:36 AM, Sam Tarakajian <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/463>.
>



-- 
http://www.mearaoreilly.com
