### ISSUE TITLE
Pulse outlines are still pixelated at some scales

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#479]

**Comment by starakaj** [comment]
Yeah I know. I actually just made a nice fix for this, but I need to push it

**Comment by mearabai** [comment]
Great! Yeah, I thought you had but wasn't seeing it so wanted to make sure

On Sat, Mar 7, 2015 at 1:09 PM, Sam Tarakajian <notifications@github.com>
wrote:

> Yeah I know. I actually just made a nice fix for this, but I need to push
> it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/479#issuecomment-77710243>.
>



-- 
http://www.mearaoreilly.com

**Comment by mearabai** [comment]
This is looking much better. Closing until further notice
