### ISSUE TITLE
Kaitlyn says new beta build keeps crashing when she goes to settings :(

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#484]

**Comment by starakaj** [comment]
She had a mega old build installed on her phone, so it's possible that she needs to delete and reinstall to clear up some kruft

**Comment by mearabai** [comment]
I'll let her know, thanks.

On Fri, Mar 6, 2015 at 11:04 AM, Sam Tarakajian <notifications@github.com>
wrote:

> She had a mega old build installed on her phone, so it's possible that she
> needs to delete and reinstall to clear up some kruft
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/484#issuecomment-77615973>.
>



-- 
http://www.mearaoreilly.com
