### ISSUE TITLE
Send new links to beta testers

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#487]
There's a list of everyone I sent it to this time here: https://docs.google.com/document/d/1Twr-Rn4LgC6O4sa97P-wt3mUMp63zoq-v51DE5bWEAA/edit#bookmark=id.jvdsdowaj3zh I also sent it to all previous testers as well.

**Comment by mearabai** [comment]
Oh ok, all previous testers minus Daniel. I'm too scared to contact him further.

**Comment by starakaj** [comment]
k. I'll talk to the beast myself.
