### ISSUE TITLE
Sync to external MIDI clock

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#79]
That's a feature we should totally have. Am I right? Yes.

**Comment by starakaj** [comment]
How hard can this possibly be?

**Comment by starakaj** [comment]
Making progress. Need to work out a couple bugs surrounding picking a particular MIDI source

**Comment by starakaj** [comment]
This is going to blow your mind (certainly it blew mine) but this is actually ready to test. Give it a spin.

**Comment by mearabai** [comment]
This is so awesome, you da man.
