### ISSUE TITLE
Tweak envelope controls for timbre

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#83]
See Ableton Operator

**Comment by mearabai** [comment]
What does this mean?  (She says, her ears perked at the mention of envelopes ;)

**Comment by mearabai** [comment]
Ok, I still don't know what this is referring to so I'm not gonna close it. (Yes I'm being a hall monitor rn).

**Comment by starakaj** [comment]
Idk. I'm going to close it because it doesn't look like it's helping anybody except maybe by adding confusion.
