### ISSUE TITLE
Need some kind of little jiggle when we change necklaces

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#90]
Removing the whiplash effect is good, but we should replace it with something that makes it more clear when we've changed from looking at one single necklace to another. Maybe a little animation, yo.

**Comment by starakaj** [comment]
I think I can do something tasteful. Let me show you

**Comment by starakaj** [comment]
What do you think? Too subtle? Not subtle enough?

**Comment by mearabai** [comment]
I think subtle is actually better. Let's leave this for now unless someone
expresses confusion at having smooth transitions when you change necklaces.

On Wed, Feb 11, 2015 at 3:59 PM, Sam Tarakajian <notifications@github.com>
wrote:

> What do you think? Too subtle? Not subtle enough?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/starakaj/rnecklace/issues/90#issuecomment-73991663>.
>



-- 
http://www.mearaoreilly.com
